"""Profile-scoped installer for the Hermes Agent 0.19.0 compatibility bridge."""
from __future__ import annotations

import argparse
import json
import os
import stat
from contextlib import contextmanager
from pathlib import Path
from typing import Dict, Iterator


@contextmanager
def _close_fd(fd: int) -> Iterator[int]:
    try:
        yield fd
    finally:
        os.close(fd)


_BRIDGE = """# Generated by MemKraft's Hermes Agent 0.19.0 bridge installer.
from memkraft.hermes_provider import MemKraftMemoryProvider


def register(ctx):
    ctx.register_memory_provider(MemKraftMemoryProvider())
"""


def install_bridge(hermes_home: Path, *, hermes_version: str) -> Dict[str, str]:
    """Install the scanner-visible 0.19.0 bridge without overwriting other code."""
    if hermes_version == "0.20.1":
        raise ValueError("Hermes Agent 0.20.1 uses entry-point discovery; remove any old bridge")
    if hermes_version != "0.19.0":
        raise ValueError("only the verified Hermes Agent 0.19.0 bridge can be installed")

    if not getattr(os, "O_NOFOLLOW", 0) or not getattr(os, "O_DIRECTORY", 0):
        raise RuntimeError("secure bridge installation is unavailable on this platform")
    if os.open not in os.supports_dir_fd or os.mkdir not in os.supports_dir_fd:
        raise RuntimeError("secure directory-relative installation is unavailable on this platform")

    home = Path(os.path.abspath(os.fspath(Path(hermes_home).expanduser())))
    plugins_dir = home / "plugins"
    plugin_dir = plugins_dir / "memkraft"
    bridge = plugin_dir / "__init__.py"
    encoded = _BRIDGE.encode("utf-8")
    directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW

    root_fd = os.open(os.path.sep, directory_flags)
    try:
        current_fd = root_fd
        for component in home.parts[1:]:
            try:
                next_fd = os.open(component, directory_flags, dir_fd=current_fd)
            except OSError as exc:
                if current_fd != root_fd:
                    os.close(current_fd)
                raise RuntimeError("refusing symbolic link or insecure Hermes home: {}".format(home)) from exc
            if current_fd != root_fd:
                os.close(current_fd)
            current_fd = next_fd
        home_fd = current_fd
        try:
            home_info = os.fstat(home_fd)
            if home_info.st_uid != os.getuid() or home_info.st_mode & 0o022:
                raise RuntimeError("refusing unowned or insecure Hermes home: {}".format(home))
            try:
                os.mkdir("plugins", mode=0o700, dir_fd=home_fd)
            except FileExistsError:
                pass
            try:
                plugins_fd = os.open("plugins", directory_flags, dir_fd=home_fd)
            except OSError as exc:
                raise RuntimeError("refusing symbolic link or insecure plugins directory: {}".format(plugins_dir)) from exc

            with _close_fd(plugins_fd):
                plugins_info = os.fstat(plugins_fd)
                if plugins_info.st_uid != os.getuid() or plugins_info.st_mode & 0o022:
                    raise RuntimeError("refusing unowned or insecure plugins directory: {}".format(plugins_dir))
                created_dir = False
                try:
                    os.mkdir("memkraft", mode=0o700, dir_fd=plugins_fd)
                    created_dir = True
                except FileExistsError:
                    pass
                try:
                    plugin_fd = os.open("memkraft", directory_flags, dir_fd=plugins_fd)
                except OSError as exc:
                    raise RuntimeError("refusing symbolic link plugin directory: {}".format(plugin_dir)) from exc

                with _close_fd(plugin_fd):
                    directory_info = os.fstat(plugin_fd)
                    if not stat.S_ISDIR(directory_info.st_mode) or directory_info.st_uid != os.getuid():
                        raise RuntimeError("refusing existing unowned plugin directory: {}".format(plugin_dir))
                    if directory_info.st_mode & 0o022:
                        raise RuntimeError("refusing insecure plugin directory permissions: {}".format(plugin_dir))
                    entries = os.listdir(plugin_fd)
                    if not created_dir:
                        if entries != ["__init__.py"]:
                            raise RuntimeError("refusing existing unowned plugin directory: {}".format(plugin_dir))
                        try:
                            file_fd = os.open(
                                "__init__.py", os.O_RDONLY | os.O_NOFOLLOW, dir_fd=plugin_fd
                            )
                        except OSError as exc:
                            raise RuntimeError("refusing symbolic link plugin bridge: {}".format(bridge)) from exc
                        with os.fdopen(file_fd, "rb") as handle:
                            file_info = os.fstat(handle.fileno())
                            if not stat.S_ISREG(file_info.st_mode) or file_info.st_uid != os.getuid():
                                raise RuntimeError("refusing existing unowned plugin: {}".format(bridge))
                            if file_info.st_mode & 0o022:
                                raise RuntimeError("refusing insecure plugin permissions: {}".format(bridge))
                            if handle.read() != encoded:
                                raise RuntimeError("refusing to overwrite existing unowned plugin: {}".format(bridge))
                        return {"action": "unchanged", "hermes_home": str(home), "path": str(bridge)}

                    file_fd = os.open(
                        "__init__.py",
                        os.O_CREAT | os.O_EXCL | os.O_WRONLY | os.O_NOFOLLOW,
                        0o600,
                        dir_fd=plugin_fd,
                    )
                    try:
                        with os.fdopen(file_fd, "wb") as handle:
                            file_fd = -1
                            handle.write(encoded)
                            handle.flush()
                            os.fsync(handle.fileno())
                    except BaseException:
                        if file_fd >= 0:
                            os.close(file_fd)
                        try:
                            os.unlink("__init__.py", dir_fd=plugin_fd)
                        except OSError:
                            pass
                        raise
                    return {"action": "installed", "hermes_home": str(home), "path": str(bridge)}
        finally:
            if home_fd != root_fd:
                os.close(home_fd)
    finally:
        os.close(root_fd)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install MemKraft's profile-scoped Hermes Agent 0.19.0 bridge."
    )
    parser.add_argument("--hermes-home", required=True, type=Path)
    parser.add_argument("--hermes-version", required=True)
    args = parser.parse_args()
    print(json.dumps(install_bridge(args.hermes_home, hermes_version=args.hermes_version), sort_keys=True))


if __name__ == "__main__":
    main()
