"""Profile-scoped installer for the Hermes Agent 0.19.0 compatibility bridge."""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Dict


_BRIDGE = """# Generated by MemKraft's Hermes Agent 0.19.0 bridge installer.
from memkraft.hermes_provider import MemKraftMemoryProvider


def register(ctx):
    ctx.register_memory_provider(MemKraftMemoryProvider())
"""


def install_bridge(hermes_home: Path, *, hermes_version: str) -> Dict[str, str]:
    """Install the scanner-visible 0.19.0 bridge without overwriting other code."""
    if hermes_version == "0.20.1":
        raise ValueError("Hermes Agent 0.20.1 uses entry-point discovery; remove any old bridge")
    if hermes_version != "0.19.0":
        raise ValueError("only the verified Hermes Agent 0.19.0 bridge can be installed")

    home = Path(hermes_home).expanduser().resolve()
    bridge = home / "plugins" / "memkraft" / "__init__.py"
    encoded = _BRIDGE.encode("utf-8")
    action = "installed"
    if bridge.exists():
        if bridge.read_bytes() != encoded:
            raise RuntimeError("refusing to overwrite existing unowned plugin: {}".format(bridge))
        action = "unchanged"
    else:
        bridge.parent.mkdir(parents=True, exist_ok=True)
        bridge.write_bytes(encoded)
        try:
            os.chmod(bridge, 0o600)
        except OSError:
            pass
    return {"action": action, "hermes_home": str(home), "path": str(bridge)}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install MemKraft's profile-scoped Hermes Agent 0.19.0 bridge."
    )
    parser.add_argument("--hermes-home", required=True, type=Path)
    parser.add_argument("--hermes-version", required=True)
    args = parser.parse_args()
    print(json.dumps(install_bridge(args.hermes_home, hermes_version=args.hermes_version), sort_keys=True))


if __name__ == "__main__":
    main()
